(function($){"use strict";function handlePreloader(){if($('.preloader').length){$('.preloader').delay(0).fadeOut(500);}}
function headerStyle(){if($('.main-header').length){var windowpos=$(window).scrollTop();var siteHeader=$('.main-header');var scrollLink=$('.scroll-to-top');if(windowpos>=250){siteHeader.addClass('fixed-header');scrollLink.fadeIn(300);}else{siteHeader.removeClass('fixed-header');scrollLink.fadeOut(300);}}}
headerStyle();if($('.main-header .navigation li.dropdown ul').length){$('.main-header .navigation li.dropdown').append('<div class="dropdown-btn"><span class="fa fa-angle-down"></span></div>');$('.main-header .navigation li.dropdown .dropdown-btn').on('click',function(){$(this).prev('ul').slideToggle(500);});$('.navigation li.dropdown > a').on('click',function(e){e.preventDefault();});}
if($('.custom-select-box').length){$('.custom-select-box').selectmenu().selectmenu('menuWidget').addClass('overflow');}
if($('input.date-time-picker').length){jQuery('input.date-time-picker').datetimepicker();}
if($('.hide-form-btn').length){$('.hide-form-btn,.prod-thumbs-carousel .thumb-box').on('click',function(e){e.preventDefault();$('.schedule-drive-outer').fadeOut(300);});}
if($('.quantity-spinner').length){$("input.quantity-spinner").TouchSpin({verticalbuttons:true});}
if($('.count-box').length){$('.count-box').appear(function(){var $t=$(this),n=$t.find(".count-text").attr("data-stop"),r=parseInt($t.find(".count-text").attr("data-speed"),10);if(!$t.hasClass("counted")){$t.addClass("counted");$({countNum:$t.find(".count-text").text()}).animate({countNum:n},{duration:r,easing:"linear",step:function(){$t.find(".count-text").text(Math.floor(this.countNum));},complete:function(){$t.find(".count-text").text(this.countNum);}});}},{accY:0});}
if($('.two-item-carousel').length){$('.two-item-carousel').owlCarousel({navigation:true,loop:true,margin:30,nav:true,smartSpeed:700,autoplay:4000,navText:['<span class="fa fa-angle-left"></span>','<span class="fa fa-angle-right"></span>'],responsive:{0:{items:1},600:{items:1},800:{items:1},1024:{items:2},1200:{items:2}}});}
if($('.four-item-carousel').length){$('.four-item-carousel').owlCarousel({navigation:true,loop:true,margin:30,nav:true,smartSpeed:700,autoplay:4000,navText:['<span class="fa fa-angle-left"></span>','<span class="fa fa-angle-right"></span>'],responsive:{0:{items:1},600:{items:2},800:{items:2},1024:{items:3},1200:{items:4}}});}
if($('.tabs-box').length){$('.tabs-box .tab-buttons .tab-btn').on('click',function(e){e.preventDefault();var target=$($(this).attr('data-tab'));if($(target).is(':visible')){return false;}else{target.parents('.tabs-box').find('.tab-buttons').find('.tab-btn').removeClass('active-btn');$(this).addClass('active-btn');target.parents('.tabs-box').find('.tabs-content').find('.tab').fadeOut(0);target.parents('.tabs-box').find('.tabs-content').find('.tab').removeClass('active-tab');$(target).fadeIn(300);$(target).addClass('active-tab');}});}
if($('.single-item-carousel').length){$('.single-item-carousel').owlCarousel({navigation:true,loop:true,margin:10,nav:true,smartSpeed:700,autoplay:5000,navText:['<span class="fa fa-angle-left"></span>','<span class="fa fa-angle-right"></span>'],responsive:{0:{items:1},600:{items:1},1200:{items:1}}});}
if($('.datepicker').length){$('.datepicker').datepicker();}
if($('.inventory-details .details-panel-box .panel-header').length){$(".inventory-details .details-panel-box .panel-header").on('click',function(){var target=$(this).next('.panel-content');$(target).slideToggle();});}
if($('.accordion-box').length){$(".accordion-box").on('click','.acc-btn',function(){var outerBox=$(this).parents('.accordion-box');var target=$(this).parents('.accordion');if($(this).hasClass('active')!==true){$(outerBox).find('.accordion .acc-btn').removeClass('active');}
if($(this).next('.acc-content').is(':visible')){return false;}else{$(this).addClass('active');$(outerBox).children('.accordion').removeClass('active-block');$(outerBox).find('.accordion').children('.acc-content').slideUp(300);target.addClass('active-block');$(this).next('.acc-content').slideDown(300);}});}
if($('.three-item-carousel').length){$('.three-item-carousel').owlCarousel({navigation:true,loop:true,margin:30,nav:true,smartSpeed:700,autoplay:5000,navText:['<span class="fa fa-angle-left"></span>','<span class="fa fa-angle-right"></span>'],responsive:{0:{items:1},600:{items:1},778:{items:2},800:{items:2},1024:{items:3},1200:{items:3},}});}
if($('.price-range-slider').length){$(".price-range-slider").slider({range:true,min:0,max:90,values:[8,85],slide:function(event,ui){$("input.property-amount").val(ui.values[0]+" - "+ui.values[1]);}});$("input.property-amount").val($(".price-range-slider").slider("values",0)+" - $"+$(".price-range-slider").slider("values",1));}
if($('.testimonial-carousel').length){$('.testimonial-carousel').owlCarousel({navigation:true,loop:true,margin:30,nav:true,smartSpeed:700,autoplay:5000,navText:['<span class="fa fa-angle-left"></span>','<span class="fa fa-angle-right"></span>'],responsive:{0:{items:1},600:{items:1},778:{items:2},1024:{items:3},1200:{items:3},}});}
if($('.prod-image-carousel').length&&$('.prod-thumbs-carousel').length){var $sync3=$(".prod-image-carousel"),$sync4=$(".prod-thumbs-carousel"),flag=false,duration=500;$sync3.owlCarousel({navigation:true,loop:false,items:1,margin:10,nav:false,navText:['<span class="fa fa-angle-left"></span>','<span class="fa fa-angle-right"></span>'],dots:false,autoplay:false,autoplayTimeout:5000}).on('changed.owl.carousel',function(e){if(!flag){flag=false;$sync4.trigger('to.owl.carousel',[e.item.index,duration,true]);flag=false;}});$sync4.owlCarousel({navigation:true,loop:false,margin:15,items:1,nav:false,navText:['<span class="icon fa fa-angle-left"></span>','<span class="icon fa fa-angle-right"></span>'],dots:false,center:false,autoplay:false,autoplayTimeout:5000,responsive:{0:{items:2,autoWidth:false},400:{items:3,autoWidth:false},600:{items:4,autoWidth:false},1024:{items:4,autoWidth:false},1200:{items:5,autoWidth:false}},}).on('click','.owl-item',function(){$sync3.trigger('to.owl.carousel',[$(this).index(),duration,true]);}).on('changed.owl.carousel',function(e){if(!flag){flag=true;$sync3.trigger('to.owl.carousel',[e.item.index,duration,true]);flag=false;}});}
if($('.lightbox-image').length){$('.lightbox-image').fancybox({openEffect:'fade',closeEffect:'fade',helpers:{media:{}}});}
if($('#contact-form').length){$('#contact-form').validate({rules:{username:{required:true},email:{required:true,email:true},phone:{required:true},message:{required:true}}});}
if($('.scroll-to-target').length){$(".scroll-to-target").on('click',function(){var target=$(this).attr('data-target');$('html, body').animate({scrollTop:$(target).offset().top},1000);});}
if($('.wow').length){var wow=new WOW({boxClass:'wow',animateClass:'animated',offset:0,mobile:false,live:true});wow.init();}
$(window).on('scroll',function(){headerStyle();});$(window).on('load',function(){handlePreloader();});})(window.jQuery);